# Generated by Django 5.1.7 on 2025-04-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_alter_category_options_category_friendly_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occasion',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
