# Generated by Django 5.1.7 on 2025-04-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_occasion_friendly_name_alter_occasion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
