# Generated by Django 5.1.7 on 2025-04-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
        ('gifts', '0004_gift_has_sizes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gift',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='gifts.gift'),
        ),
    ]
